[package]
name = "Michael-F-bryan/wcgi-python-template"
version = "0.1.0"
description = "A PHP template for WCGI applications"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/wasmerio/wcgi-php-template"

[[module]]
name = "php"
source = "php-cgi.wasm"
abi = "wasi"

[[command]]
name = "php"
runner = "https://webc.org/runner/wcgi"
module = "php"
annotations = { wcgi = { dialect = "rfc-3875" } }

[fs]
"app" = "app"
